name: Build Python application

on:
  workflow_dispatch:

jobs:
  lint-python:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        name: Checkout
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Install pipx
        run: |
          apt update
          apt install -y pipx python3-venv
          pipx ensurepath
      - name: Install poetry and ruff # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
        run: pipx install poetry
      - uses: actions/setup-python@55aad42e4674b58b2b2fb7d8e7552402d922b4e7 # v5.3.0
        with:
          python-version: '3.13'
          cache: 'poetry'

